### PR TITLE
Bug Fix and other features

### PR DESCRIPTION
**Pull request by KirichenkoND**
1. Fix a problem with the character's flight
2. Fix a problem with the ESP
3. Added colors for ESP
3.1. Enemy - red
3.2. Items - yellow
3.3. Players - white

### CODE REVIEW

**Comment by SkyTheDragonDev** [comment]
How do I get this in the actual mod menu files?

**Comment by KirichenkoND** [comment]
Approve my changes.

**Comment by Gauvino** [comment]
Me too how i build a new dll with the new change ?

**Comment by cluzier** [comment]
> How do I get this in the actual mod menu files?

On the main page of this repository, you can see on the right hand side a section that is titled, "Releases" click that and download the .dll file and place into your plugins folder.

Hope this helps!

**Pull request closed without merging**
